name: listen_portfolio_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management & DI
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Networking
  dio: ^5.4.3+1
  retrofit: ^4.9.2

  # Functional Programming
  fpdart: ^1.1.0

  # Storage
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2

  # Utilities
  logger: ^2.3.0
  url_launcher: ^6.2.1
  connectivity_plus: ^6.0.3
  intl: ^0.19.0

  # Routing
  go_router: ^14.2.0
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5

  # Testing
  mocktail: ^1.0.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/ic_launcher_adaptive_fore.png"
  adaptive_icon_background: "#448AFF"
  adaptive_icon_foreground: "assets/images/ic_launcher_adaptive_fore.png"
  adaptive_icon_foreground_inset: 16

flutter:
  uses-material-design: true
  assets:
    - assets/images/
